### ISSUE TITLE
Heres the website btw. LOL

### ISSUE THREAD

**Issue by dotslashlevi** [Client-Archive/ExileClient#1]
not an issue i have to agree, they deserve this. Lemme leak the website too.
[shit.zip](https://github.com/Client-Archive/ExileClient/files/9909997/shit.zip)

**Comment by dotslashlevi** [comment]
yeah. its like 1kb, i don't have the latest version sadly

**Comment by yawfi** [comment]
i dont code html shit was ass af

**Comment by Noxiuam** [comment]
the whole client was

**Comment by dotslashlevi** [comment]
😭

**Comment by yawfi** [comment]
@dotslashlevi love you bunches :) thanks for the "help" with the website LMAO, I barely know any html so I take blame for the shit website, but honestly the client was shit until nox came and redid EVERYTHING by himself, and got underpaid... honestly for that work that he did prob deserve at least $25, I mean he spent 7+ hours on the client and it fails bc of shit mistakes, and wasn't paid enough... the client woulda had potential if I knew what I was doing at the time, and same with the management & staff.

**Comment by dotslashlevi** [comment]
@yawfi i have to agree, i hardly know html and we would have been better off using namelessmc LOL. not sure why savrien is known when he does shit like that LMAOO
